In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns

In [2]:
import glob
path = r'C:\Users\aanak\OneDrive\Desktop\Materials for college\Crypto-Forecasting\data'
all_files = glob.glob(path + "/*csv")
all_files
df = pd.concat((pd.read_csv(f) for f in all_files))
df

,Numero,Nom,Simbol,Cap de mercat,Preu,Oferta circulant,Volum 24 hores,% 1h,% 2h,% 7d
0,1,Bitcoin,BTC,"$94,426,076,779",$5681.43,"16,620,125","$3,867,720,000",0.43%,11.61%,29.76%
1,2,Ethereum,ETH,"$31,006,174,813",$326.10,"95,083,257","$1,003,690,000",0.14%,6.28%,8.99%
2,3,Ripple,XRP,"$9,586,229,114",$0.248345,"38,600,451,446*","$380,544,000",0.96%,-4.39%,4.70%
3,4,Bitcoin Cash,BCH,"$5,197,422,996",$311.32,"16,694,525","$345,263,000",-1.09%,-1.01%,-15.23%
4,5,Litecoin,LTC,"$3,086,414,300",$57.85,"53,350,082","$510,038,000",1.67%,12.10%,10.82%
...,...,...,...,...,...,...,...,...,...,...
1260,1261,ETXEtherx,ETX,?,$1.76,?*,Low Vol,?,-0.39%,?
1261,1262,XTDXTD Coin,XTD,?,$0.000074,?,Low Vol,?,?,15.84%
1262,1263,DMCDynamicCoin,DMC,?,$1.00,?,?,?,?,?
1263,1264,MIUMIYUCoin,MIU,?,$0.000071,?,?,?,?,?
1264,1265,INFInfChain,INF,?,$0.007269,?,?,?,?,0.44%

In [3]:
df.shape

(35428, 10)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35428 entries, 0 to 1264
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Numero            35428 non-null  int64
 1   Nom               35428 non-null  object
 2   Simbol            35428 non-null  object
 3   Cap de mercat     35428 non-null  object
 4   Preu              35428 non-null  object
 5   Oferta circulant  35428 non-null  object
 6   Volum 24 hores    35428 non-null  object
 7   % 1h              35428 non-null  object
 8   % 2h              35428 non-null  object
 9   % 7d              35428 non-null  object
dtypes: int64(1), object(9)
memory usage: 3.0+ MB

In [5]:
df.describe()

             Numero
count  35428.000000
mean     612.180450
std      354.163021
min        1.000000
25%      306.000000
50%      611.000000
75%      917.000000
max     1324.000000